export const metadata = {
  title: "About",
  description: "Generated by create next app",
};
export default function About() {
  return (
    <>
      <div className="mx-auto container">
        <h1 className="text-white text-3xl font-bold leading-10">About</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores
          suscipit, et iste dolorem, mollitia ea laudantium ratione beatae quas
          porro culpa ab ipsa ducimus minus voluptates dolore quidem quasi
          accusamus architecto expedita vero nesciunt! Accusantium, recusandae
          maxime enim laudantium ipsa rerum reiciendis eaque ratione optio earum
          autem sit, eum tenetur.
        </p>
      </div>
    </>
  );
}
