export const metadata = {
    title: 'About',
    description: 'Generated by create next app',
  }
export default function About() {
  return (
    <>
      <div className="mx-auto">
        <h1>About</h1>
      </div>
    </>
  );
}
