export const metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function Blog() {
  return <>
  <div className="container mx-auto">
    <h1>Blogs</h1>
  </div>
  </>;
}